services:
  ollama:
    user: "${UID}:${GID}"
    image: ollama/ollama:latest
    deploy:
      resources:
        limits:
          memory: 4G
    container_name: argos-ollama
    ports: ["11434:11434"]
    volumes: ["./ollama_data:/root/.ollama"]
    

  hermes:
    user: "${UID}:${GID}"
    deploy:
      resources:
        limits:
          memory: 512M
    build: .
    container_name: argos-hermes
    ports: ["8080:8080"]
    volumes: ["./hermes_data:/root/.hermes"]
    environment:
      - LLM_API_BASE=http://ollama:11434/v1
      - GATEWAY_ALLOW_ALL_USERS=true
    entrypoint: /bin/bash /app/init.sh
    restart: unless-stopped